auto: true

#markdown: rdiscount
highlighter: 'rouge'
#paginate: 8
permalink: /:title

title: Henry's Blog
url: http://HenryChen1.github.io
feed: /atom.xml
author_info: <a href="http://HenryChen1.github.io/">Mukosame</a>
